Ocp 689 config from global context
ZaiusInc/app-sdk pull request #131
Opened 2024-02-21 14:44 UTC by pawelziebaopti

2024-03-08 12:47 UTC, SoAG requested changes

2024-03-12 09:33 UTC, pawelziebaopti commented on src/app/lib/CampaignEvents.ts
> +      type = getOCPContext()?.ocpRuntime?.appContext.manifest.channel?.type;
good point! changed

2024-03-12 09:36 UTC, pawelziebaopti commented on src/app/AppContext.ts
> +  if (!ocpContext) {
this is to avoid throwing error from getOCPContext to allow falling back to default settings, e.g. global context, local function api, etc. 
this method will have to be rebuilt anyway though (to allow reusing the same lib in both old and new anduin). I'm working on it

2024-03-28 12:14 UTC, SoAG approved these changes

2024-03-28 13:19 UTC, merged