OCP-811: Ensure we only send the specified limit in a batch
ZaiusInc/app-sdk pull request #137
Opened 2024-09-05 02:46 UTC by SoAG

2024-09-06 10:02 UTC, pawelziebaopti approved these changes

2024-09-06 10:03 UTC, pawelziebaopti requested changes

2024-09-06 10:03 UTC, pawelziebaopti commented on src/app/lib/tests/Batcher.test.ts
> +    it('does not cause the batch limit to be exceeded ' +
this doesn't really check the limit. the limit is 5 and it flushes after adding only 2 items.

2024-09-06 12:35 UTC, SoAG commented on src/app/lib/tests/Batcher.test.ts
> +    it('does not cause the batch limit to be exceeded ' +
have another look

2024-09-09 07:41 UTC, pawelziebaopti approved these changes

2024-09-09 07:41 UTC, pawelziebaopti requested changes
don't you have to bump the version as well?

2024-09-09 11:59 UTC, SoAG commented
done

2024-09-12 07:39 UTC, pawelziebaopti approved these changes

2024-09-12 12:41 UTC, merged